service: typescript-http-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  timeout: 10
  logs:
    httpApi: true
  httpApi:
    # metrics: true # Enable if you need
    cors: true

functions:
  app:
    handler: src/handler.handler
    # reservedConcurrency: 100
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

plugins:
  - serverless-plugin-typescript
